# Generated by Django 6.0.1 on 2026-07-12 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the driver', max_length=150)),
                ('license_number', models.CharField(help_text='Unique driving license number', max_length=50, unique=True)),
                ('license_category', models.CharField(choices=[('LMV', 'Light Motor Vehicle'), ('HMV', 'Heavy Motor Vehicle')], default='LMV', max_length=10)),
                ('license_expiry_date', models.DateField(help_text='Date when the driving license expires')),
                ('contact_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('safety_score', models.PositiveIntegerField(default=100, help_text='Driver safety score out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On Trip'), ('OFF_DUTY', 'Off Duty'), ('SUSPENDED', 'Suspended')], db_index=True, default='AVAILABLE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
