# Generated by Django 6.0.7 on 2026-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_file',
            field=models.FileField(blank=True, help_text='Uploaded copy of the driving license', null=True, upload_to='driver_licenses/'),
        ),
    ]
