# Generated by Django 6.0.7 on 2026-07-12 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=100)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Completed", "Completed")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="vehicle_app.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
