# Generated by Django 6.0.7 on 2026-07-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("trip_app", "0003_trip_final_odometer_trip_fuel_consumed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuellog",
            name="cost_per_liter",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="fuellog",
            name="trip",
            field=models.OneToOneField(
                blank=True,
                help_text="The trip this fuel was consumed on.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuel_log",
                to="trip_app.trip",
            ),
        ),
    ]
