# Generated by Django 6.0.7 on 2026-07-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_no", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Van", "Van"),
                            ("Truck", "Truck"),
                            ("Mini", "Mini"),
                            ("Bus", "Bus"),
                        ],
                        default="Van",
                        max_length=20,
                    ),
                ),
                ("capacity", models.CharField(max_length=50)),
                ("odometer", models.PositiveIntegerField(default=0)),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("On Trip", "On Trip"),
                            ("In Shop", "In Shop"),
                            ("Retired", "Retired"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
