# Generated by Django 6.0.7 on 2026-07-12 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('RC', 'Registration Certificate (RC)'), ('DL', 'Driving Licence (DL)'), ('Insurance', 'Motor Insurance Policy'), ('PUC', 'Pollution Under Control (PUC) Certificate'), ('Permit_Fitness', 'Commercial Permits & Fitness Certificate')], max_length=50)),
                ('file', models.FileField(upload_to='vehicle_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicle_app.vehicle')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('vehicle', 'document_type')},
            },
        ),
    ]
