# Generated by Django 6.0.1 on 2026-07-12 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_app', '0001_initial'),
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('source', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('cargo_weight', models.PositiveIntegerField(help_text='Cargo weight in kg.')),
                ('planned_distance', models.PositiveIntegerField(help_text='Planned distance in km.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(help_text='Select an available driver.', on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='driver_app.driver')),
                ('vehicle', models.ForeignKey(help_text='Select an available vehicle.', on_delete=django.db.models.deletion.RESTRICT, related_name='trips', to='vehicle_app.vehicle')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
