# Generated by Django 6.0.1 on 2026-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Expected revenue from this trip in INR (₹).', max_digits=10),
        ),
    ]
