# Generated by Django 6.0.7 on 2026-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trip_app", "0002_trip_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="final_odometer",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Final odometer reading (km) when trip completed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_consumed",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total fuel consumed during trip (liters).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_cost_per_liter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fuel price per liter at time of completion (₹).",
                max_digits=8,
                null=True,
            ),
        ),
    ]
