# Generated by Django 6.0.7 on 2026-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_key", models.CharField(max_length=50, unique=True)),
                ("role_name", models.CharField(max_length=100)),
                ("fleet", models.CharField(default="—", max_length=10)),
                ("driver", models.CharField(default="—", max_length=10)),
                ("trips", models.CharField(default="—", max_length=10)),
                ("fuel", models.CharField(default="—", max_length=10)),
                ("analytics", models.CharField(default="—", max_length=10)),
            ],
        ),
    ]
